[package]
name = "ryg"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.13", features = ["full"] }
pretty_env_logger = { version = "^0.4" }

eng = { version = "^0.1", git = "https://github.com/dlunch/eng" }
